### ISSUE TITLE
Задание по 6 работе

### ISSUE THREAD

**Issue by JAkutenshi** [2-Overheal-2/ORG-EVM#3]
0. Загрузить pdf
1. Игнорировать ограничения из таблицы задания
2. Пример 
```
N = 10 
Xmin = -1 
Xmax = 1
Ngr = 3
Lgr = [-1 0 1]
```

Ожидаемый вывод: кол-во сгенерированых -1, кол-во сгенерированых 0 и кол-во сгенерированых 1
3. Задание: дополнительно посчитать сумму чисел по каждому интервалу

**Comment by 2-Overheal-2** [comment]
Задание выполнено!
